services:
  fastapi:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    env_file:
      - ./server/.env
    tty: true
    restart: always

networks:
  default:
    external: true
    name: CloudflareTunnel